//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public string DonVi { get; set; }
        public Nullable<int> GiaMua { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public string NhomHang { get; set; }
        public string TenKho { get; set; }
        public Nullable<bool> ConQuanLy { get; set; }
        public Nullable<int> TonKho { get; set; }
        public string NCC { get; set; }
    }
}
