//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuBanHang
    {
        public string MaBH { get; set; }
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string TenNV { get; set; }
        public string TenKho { get; set; }
        public string DiaChi { get; set; }
        public string GhiChu { get; set; }
        public string DienThoai { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> TongTien { get; set; }
    }
}
